# Generated by Django 2.1.7 on 2019-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_submissions_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions_demo',
            name='verbose',
            field=models.BooleanField(),
        ),
    ]
