# Generated by Django 2.1.7 on 2019-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190417_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions_demo',
            name='task_result',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissions_demo',
            name='task_status',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
