# Generated by Django 2.1.7 on 2019-05-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190417_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.DateTimeField(auto_now=True, verbose_name='Edit the date')),
                ('data_name', models.CharField(max_length=64)),
                ('data_path', models.CharField(max_length=128)),
            ],
        ),
    ]
