# Generated by Django 2.1.7 on 2019-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190513_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_demo',
            name='data_id',
            field=models.CharField(max_length=64),
        ),
    ]
