# Generated by Django 2.1.7 on 2019-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190513_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions_demo',
            name='project_name',
            field=models.CharField(default='sz_with_sfmri', max_length=64),
            preserve_default=False,
        ),
    ]
