# Generated by Django 2.1.7 on 2019-05-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_submissions_demo_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions_demo',
            name='test_data',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='submissions_demo',
            name='train_data',
            field=models.CharField(max_length=1024),
        ),
    ]
