# Generated by Django 2.1.7 on 2019-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_user_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_demo',
            name='uploader',
            field=models.CharField(default='Raniac', max_length=32),
            preserve_default=False,
        ),
    ]
