# Generated by Django 2.1.7 on 2019-06-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_data_demo_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_demo',
            name='data_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='submissions_demo',
            name='task_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
