# Generated by Django 2.1.7 on 2019-07-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20190624_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions_demo',
            name='enable_test',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
