# Generated by Django 2.1.7 on 2019-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_projects_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_demo',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
