# Generated by Django 2.1.7 on 2019-07-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20190727_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects_demo',
            old_name='data_templates_url',
            new_name='templates_url',
        ),
        migrations.RenameField(
            model_name='projects_demo',
            old_name='workflow_templates_url',
            new_name='workflows_url',
        ),
    ]
