# Generated by Django 2.1.7 on 2019-09-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_data_projects_submissions_user_proj_auth_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Datasets',
        ),
    ]
