# Generated by Django 2.1.7 on 2019-09-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20190925_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasets',
            name='data_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
