# Generated by Django 2.1.7 on 2019-10-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_datasets_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='admin_id',
            field=models.CharField(default='USER00000000000000', max_length=32),
            preserve_default=False,
        ),
    ]
